- include: install.deb.yml
  when: ansible_os_family == 'Debian'

- include: install.arch.yml
  when: ansible_pkg_mgr == 'pacman'

- name: ensure golang directory exists
  file: path={{ golang_path }} state=directory
