- name: ensure python development library headers are installed
  apt: name=python3-dev state=latest
  sudo: yes

- name: ensure python setup-tools is installed
  apt: name=python-setuptools state=present
  sudo: yes

- name: install pip
  easy_install: name=pip
  sudo: yes

- name: upgrade pip
  pip: name=pip state=latest
  sudo: yes

- name: install virtualenv
  pip: name=virtualenv state=latest
  sudo: yes

- name: install virtualenvwrapper
  pip: name=virtualenvwrapper state=latest
  sudo: yes
