- include: install.deb.yml
  when: ansible_os_family == 'Debian'

- include: install.arch.yml
  when: ansible_pkg_mgr == 'pacman'

- name: install pip
  easy_install: name=pip
  sudo: yes

- name: install and upgrade python packages
  pip: name={{ item }} state=latest
  sudo: yes
  with_items:
      - pip
      - virtualenv
      - virtualenvwrapper
      - isort
      - flake8
      - pylint
      - ptpython
      - pyenv
