- include: install.deb.yml
  when: ansible_os_family == 'Debian'

- include: install.arch.yml
  when: ansible_pkg_mgr == 'pacman'

- name: install oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest={{ ansible_env.HOME }}/.oh-my-zsh

- name: be sure zsh is configured
  template: src=zshrc.j2 dest={{ ansible_env.HOME }}/.zshrc owner={{ ansible_user_id }}
