- include: install.deb.yml
  when: ansible_os_family == 'Debian'

- include: install.arch.yml
  when: ansible_pkg_mgr == 'pacman'

- name: be sure tmux is configured
  copy: src=tmux.conf dest={{ ansible_env.HOME }}/.tmux.conf owner={{ ansible_user_id }}
