- name: ensure vim is installed
  apt: name=vim-gnome state=present
  sudo: yes

- name: be sure vim is configured
  copy: src=vimrc dest={{ ansible_env.HOME }}/.vimrc owner={{ ansible_user_id }}

- name: be sure all plugins is installed
  command: vim +NeoBundleInstall! +qall
