- name: ensure vim is installed
  apt: name=vim state=present
  sudo: yes

- name: be sure vim configurations are updated
  get_url: url=https://raw.githubusercontent.com/drgarcia1986/.vimrc/minimal/.vimrc dest={{ ansible_env.HOME }}/.vimrc

- name: be sure vim color schema is configurated
  git: repo=https://github.com/tomasr/molokai.git dest={{ ansible_env.HOME }}/.vim
